 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ndrs", type: :request do
  
  # Ndr. As you add validations to Ndr, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ndr.create! valid_attributes
      get ndrs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ndr = Ndr.create! valid_attributes
      get ndr_url(ndr)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ndr_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ndr = Ndr.create! valid_attributes
      get edit_ndr_url(ndr)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ndr" do
        expect {
          post ndrs_url, params: { ndr: valid_attributes }
        }.to change(Ndr, :count).by(1)
      end

      it "redirects to the created ndr" do
        post ndrs_url, params: { ndr: valid_attributes }
        expect(response).to redirect_to(ndr_url(Ndr.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ndr" do
        expect {
          post ndrs_url, params: { ndr: invalid_attributes }
        }.to change(Ndr, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ndrs_url, params: { ndr: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ndr" do
        ndr = Ndr.create! valid_attributes
        patch ndr_url(ndr), params: { ndr: new_attributes }
        ndr.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ndr" do
        ndr = Ndr.create! valid_attributes
        patch ndr_url(ndr), params: { ndr: new_attributes }
        ndr.reload
        expect(response).to redirect_to(ndr_url(ndr))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ndr = Ndr.create! valid_attributes
        patch ndr_url(ndr), params: { ndr: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ndr" do
      ndr = Ndr.create! valid_attributes
      expect {
        delete ndr_url(ndr)
      }.to change(Ndr, :count).by(-1)
    end

    it "redirects to the ndrs list" do
      ndr = Ndr.create! valid_attributes
      delete ndr_url(ndr)
      expect(response).to redirect_to(ndrs_url)
    end
  end
end
