 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/whitelists", type: :request do
  
  # Whitelist. As you add validations to Whitelist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Whitelist.create! valid_attributes
      get whitelists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      whitelist = Whitelist.create! valid_attributes
      get whitelist_url(whitelist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_whitelist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      whitelist = Whitelist.create! valid_attributes
      get edit_whitelist_url(whitelist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Whitelist" do
        expect {
          post whitelists_url, params: { whitelist: valid_attributes }
        }.to change(Whitelist, :count).by(1)
      end

      it "redirects to the created whitelist" do
        post whitelists_url, params: { whitelist: valid_attributes }
        expect(response).to redirect_to(whitelist_url(Whitelist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Whitelist" do
        expect {
          post whitelists_url, params: { whitelist: invalid_attributes }
        }.to change(Whitelist, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post whitelists_url, params: { whitelist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested whitelist" do
        whitelist = Whitelist.create! valid_attributes
        patch whitelist_url(whitelist), params: { whitelist: new_attributes }
        whitelist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the whitelist" do
        whitelist = Whitelist.create! valid_attributes
        patch whitelist_url(whitelist), params: { whitelist: new_attributes }
        whitelist.reload
        expect(response).to redirect_to(whitelist_url(whitelist))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        whitelist = Whitelist.create! valid_attributes
        patch whitelist_url(whitelist), params: { whitelist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested whitelist" do
      whitelist = Whitelist.create! valid_attributes
      expect {
        delete whitelist_url(whitelist)
      }.to change(Whitelist, :count).by(-1)
    end

    it "redirects to the whitelists list" do
      whitelist = Whitelist.create! valid_attributes
      delete whitelist_url(whitelist)
      expect(response).to redirect_to(whitelists_url)
    end
  end
end
